# -*- coding: utf-8 -*-
"""Noor us saba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WL2UWm6pwpZGR8ZVV0_bfbI6R7Zes2WX

     **STUDENT GRADE CALCULATOR:**


marks=int(input("enter a num (1-100)"))
if marks < 1 or marks > 100:
  print("Invalid input")
elif marks < 50:
    print("Grade F")
elif marks>=50 and marks <=60:
     print("Grade E")
elif marks>=61 and marks <=70:
      print("Grade D")
elif marks>=71 and marks<=80:
       print("Grade C")
elif marks>=81 and marks<=90:
       print("Grade B")
elif marks>=91 and marks<=100:
       print("Grade A")
       

    **FACTORIAL CALCULATOR :**


num=int(input ("enter anumber:"))
if num<0:
  print("factorial is not possible")
factorial=1
i=1
while i<=num:
  factorial*=i
  i+=1

print(factorial)


        **FIBONACCI SERIES:**
        

num=int(input("enter a num :"))
a=0
b=1
i=1
while i<=num:
  print(a, end=", " if i < num else "\n")
  c=a+b
  a=b
  b=c
  i+=1
